export const decorList = [
  {
    name: "RESTAURANT",
    ko: "레스토랑",
    tags: ["amenity=restaurant"],
    emoji: "🍽️",
  },
  {
    name: "CAFE",
    ko: "카페",
    tags: ["amenity=cafe", "cuisine=coffee_shop"],
    emoji: "☕",
  },
  {
    name: "SWEET_SHOP",
    ko: "디저트 가게",
    tags: ["shop=confectionery", "shop=pastry"],
    emoji: "🍬",
  },
  {
    name: "MOVIE_THEATER",
    ko: "영화관",
    tags: ["amenity=cinema"],
    emoji: "🎬",
  },
  { name: "PHARMACY", ko: "약국", tags: ["amenity=pharmacy"], emoji: "💊" },
  { name: "ZOO", ko: "동물원", tags: ["tourism=zoo"], emoji: "🦁" },
  {
    name: "FOREST",
    ko: "숲",
    tags: ["landuse=forest", "natural=wood"],
    emoji: "🌲",
  },
  { name: "WATERSIDE", ko: "물가", tags: ["natural=water"], emoji: "🌊" },
  {
    name: "POST_OFFICE",
    ko: "우체국",
    tags: ["amenity=post_office"],
    emoji: "📮",
  },
  {
    name: "ART_GALLERY",
    ko: "미술관",
    tags: ["shop=art", "tourism=museum"],
    emoji: "🖼️",
  },
  {
    name: "AIRPORT",
    ko: "공항",
    tags: ["aeroway=aerodrome", "aeroway=heliport"],
    emoji: "✈️",
  },
  {
    name: "STATION",
    ko: "역",
    tags: ["building=train_station", "railway=station"],
    emoji: "🚉",
  },
  { name: "BEACH", ko: "해변", tags: ["natural=beach"], emoji: "🏖️" },
  {
    name: "BURGER_PLACE",
    ko: "햄버거 가게",
    tags: ["amenity=fast_food", "cuisine=burger"],
    emoji: "🍔",
  },
  {
    name: "CORNER_STORE",
    ko: "편의점",
    tags: ["shop=convenience"],
    emoji: "🏪",
  },
  {
    name: "SUPERMARKET",
    ko: "슈퍼마켓",
    tags: ["shop=supermarket"],
    emoji: "🛒",
  },
  {
    name: "BAKERY",
    ko: "베이커리",
    tags: ["cuisine=pretzel", "shop=bakery"],
    emoji: "🥐",
  },
  { name: "HAIR_SALON", ko: "미용실", tags: ["shop=hairdresser"], emoji: "💇" },
  {
    name: "CLOTHES_STORE",
    ko: "패션",
    tags: ["shop=clothes", "shop=shoes"],
    emoji: "👗",
  },
  { name: "PARK", ko: "공원", tags: ["leisure=park"], emoji: "🏞️" },
  {
    name: "LIBRARY_BOOKSTORE",
    ko: "도서관/서점",
    tags: ["amenity=library"],
    emoji: "📚",
  },
  {
    name: "SUSHI_RESTAURANT",
    ko: "초밥집",
    tags: ["cuisine=sushi"],
    emoji: "🍣",
  },
  { name: "MOUNTAIN", ko: "산", tags: ["natural=peak"], emoji: "⛰️" },
  { name: "STADIUM", ko: "스타디움", tags: ["leisure=stadium"], emoji: "🏟️" },
  {
    name: "THEME_PARK",
    ko: "테마파크",
    tags: ["tourism=theme_park"],
    emoji: "🎢",
  },
  {
    name: "BUS_STOP",
    ko: "버스 정류장",
    tags: ["highway=bus_stop"],
    emoji: "🚌",
  },
  {
    name: "ITALIAN_RESTAURANT",
    ko: "이탈리안 레스토랑",
    tags: ["cuisine=italian", "cuisine=pasta", "cuisine=pizza"],
    emoji: "🍝",
  },
  {
    name: "RAMEN_RESTAURANT",
    ko: "라멘 가게",
    tags: [
      "cuisine=chinese",
      "cuisine=noodle",
      "cuisine=ramen",
      "cuisine=soba",
      "cuisine=udon",
    ],
    emoji: "🍜",
  },
  {
    name: "BRIDGE",
    ko: "다리",
    tags: ["bridge=viaduct", "bridge=yes"],
    emoji: "🌉",
  },
  { name: "HOTEL", ko: "호텔", tags: ["tourism=hotel"], emoji: "🏨" },
  {
    name: "MAKEUP_STORE",
    ko: "화장품 가게",
    tags: ["amenity=pharmacy", "shop=cosmetics", "shop=department_store"],
    emoji: "💄",
  },
  {
    name: "SHRINE_TEMPLE",
    ko: "제단과 사찰",
    tags: [
      "building=shrine AND religion=shinto",
      "building=shrine AND religion=buddhist",
      "building=temple AND religion=shinto",
      "building=temple AND religion=buddhist",
    ],
    emoji: "⛩️",
  },
  {
    name: "APPLIANCES_STORE",
    ko: "전자제품 매장",
    tags: ["shop=appliance", "shop=computer", "shop=electronics"],
    emoji: "📺",
  },
  {
    name: "CURRY_RESTAURANT",
    ko: "카레 레스토랑",
    tags: ["cuisine=curry", "cuisine=indian", "cuisine=nepalese"],
    emoji: "🍛",
  },
  {
    name: "DIY_STORE",
    ko: "공구점",
    tags: ["shop=doityourself", "shop=hardware"],
    emoji: "🛠️",
  },
  {
    name: "UNIVERSITY_COLLEGE",
    ko: "대학 & 전문대학",
    tags: ["amenity=college", "amenity=university", "building=university"],
    emoji: "🎓",
  },
  {
    name: "MEXICAN_RESTAURANT",
    ko: "멕시코 레스토랑",
    tags: ["cuisine=mexican", "cuisine='tex-mex'"],
    emoji: "🌮",
  },
  {
    name: "LAUNDRY",
    ko: "빨래방 & 세탁소",
    tags: ["shop=dry_cleaning", "shop=laundry"],
    emoji: "🧺",
  },
  {
    name: "KOREAN_RESTAURANT",
    ko: "한식 레스토랑",
    tags: ["cuisine=korean"],
    emoji: "🍲",
  },
  {
    name: "STREET",
    ko: "길거리",
    tags: ["highway=residential"],
    emoji: "🛣",
  },
  {
    name: "STATIONERY",
    ko: "문구점",
    tags: ["shop=stationery"],
    emoji: "✏️",
  },
];

export const decorMap = Object.fromEntries(
  decorList.map((item) => [item.name, item])
);
