name: 배포

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Backend (JAR only)
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew build -x test --no-daemon --no-watch-fs

      - name: Build Frontend
        run: |
          cd frontend
          echo "${{ secrets.FRONTEND_ENV }}" > .env
          npm install
          npm run build

      - name: Copy frontend build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend/build/*"
          target: "/tmp/frontend-build"

      - name: Copy backend JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/build/libs/backend-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app/pik-one/backend"
          strip_components: 3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[백엔드 실행 준비]"
             pkill -f "java -jar" || true
             cd /home/ubuntu/app/pik-one/backend || { echo "[경로 이동 실패]"; exit 1; }

             echo "[환경변수 주입]"
             export DB_URL="${{ secrets.DB_URL }}"
             export DB_USERNAME="${{ secrets.DB_USERNAME }}"
             export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

             export NAVER_CLIENT_ID="${{ secrets.NAVER_CLIENT_ID }}"
             export NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}"
             export NAVER_REDIRECT_URI="${{ secrets.NAVER_REDIRECT_URI }}"
             export NAVER_AUTHORIZATION_GRANT_TYPE="${{ secrets.NAVER_AUTHORIZATION_GRANT_TYPE }}"
             export NAVER_AUTHORIZATION_URL="${{ secrets.NAVER_AUTHORIZATION_URL }}"
             export NAVER_TOKEN_URL="${{ secrets.NAVER_TOKEN_URL }}"
             export NAVER_USER_INFO_URL="${{ secrets.NAVER_USER_INFO_URL }}"
             export NAVER_USER_NAME_ATTRIBUTE="${{ secrets.NAVER_USER_NAME_ATTRIBUTE }}"

             export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
             export JWT_EXPIRATION_TIME="${{ secrets.JWT_EXPIRATION_TIME }}"

             export FRONTEND_URL="${{ secrets.FRONTEND_URL }}"

             echo "[Spring Boot 백엔드 실행]"
             nohup java -jar backend-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &

             sleep 5
             echo "[백엔드 로그 출력]"
             tail -n 20 log.txt

             echo "[프론트 배포]"
             sudo rm -rf /var/www/html/*
             sudo cp -r /tmp/frontend-build/* /var/www/html/
             sudo rm -rf /tmp/frontend-build
