name: 배포

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Build Frontend
        run: |
          cd frontend
          echo "${{ secrets.FRONTEND_ENV }}" > .env
          npm install
          npm run build

      - name: Copy frontend to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r frontend/build ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/frontend-build

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "[코드 최신화]"
            cd ~/backend
            git pull origin main

            echo "[.env 생성]"
            echo "${{ secrets.BACKEND_ENV }}" > ~/backend/.env

            echo "[백엔드 배포]"
            cd ~/backend
            ./deploy.sh

            echo "[프론트 배포]"
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/frontend-build/* /var/www/html/
            sudo rm -rf /tmp/frontend-build
          EOF
